:sectnums:
:sectnumlevels: 5

== Download

Go to https://www.confluent.io/download/ and download Confluent Platform. Unpack and set PATH to .../confluent-x.y.z/bin

  export PATH=/..../confluent-x.y.z/bin

== Start the Demo Cluster

    docker-compose up

== Set up Kafka Manager

=== Add cluster
Browse to http://localhost:9000. +
Click 'Cluster->Add cluster'

=== Fill in the following and leave everything else as default values

Cluster name (can be any name): kafka-docker +
Cluster Zookeeper Hosts: zk-1:2181,zk-2:2181,zk-3:2181 +
Check 'Enable JMX Polling...' +
Check 'Poll consumer information...' +

Click 'Save'

== Set up Topics

=== Create the first Topic

Delete Topic if it exists

    kafka-topics --delete \
        --if-exists \
        --topic chuck-norris-fact \
        --zookeeper localhost:2181,localhost:2182,localhost:2183

Create the first Topic

    kafka-topics --create \
        --topic chuck-norris-fact \
        --partitions 1 \
        --replication-factor 3 \
        --if-not-exists \
        --config min.insync.replicas=2 \
        --zookeeper localhost:2181,localhost:2182,localhost:2183

To verify that the creation of the topic was successful:

    kafka-topics --describe \
        --topic chuck-norris-fact \
        --zookeeper localhost:2181,localhost:2182,localhost:2183

=== Create the second Topic

Delete Topic if it exists

    kafka-topics --delete \
        --if-exists \
        --topic chuck-norris-shout-fact \
        --zookeeper localhost:2181,localhost:2182,localhost:2183

Create the second topic where the facts are shouted!

    kafka-topics --create \
        --topic chuck-norris-shout-fact \
        --partitions 1 \
        --replication-factor 3 \
        --if-not-exists \
        --config min.insync.replicas=2 \
        --zookeeper localhost:2181,localhost:2182,localhost:2183

To verify that the creation of the topic was successful:

    kafka-topics --describe \
        --topic chuck-norris-shout-fact \
        --zookeeper localhost:2181,localhost:2182,localhost:2183

The topics are now visible in Kafka-Manager, http://localhost:9000

== Start two KSQL shells and print the Topic content
    $ ksql
    print 'chuck-norris-fact';

    $ ksql
    print 'chuck-norris-shout-fact';

== Run Producer and Stream applications
Now run the two tests

  se.ryz.kafka.demo.ChuckNorrisFact.chuckNorrisFactProducer

and

    se.ryz.kafka.demo.ChuckNorrisFact.chuckNorrisFactShouter

Follow the console and see that messages are produced and consumed. Look in the KSQL shells and see that messages are being produced.


== Bonus
Go into kafka-manager ant see that the Topic 'chuck-norris-shout-fact' exists and note which broker is the leader.
Kill the leader broker.

    docker kill KAFKA_LEADER_BROKER

Start it again. Look in kafka-manager and see which broker is the leader and whether it is preferred.
Trigger a 'Preferred Replica Election' and go back to the Topic view, see that the preferred leader changed again.

