== Source
https://docs.confluent.io/current/installation/docker/docs/installation/clustered-deployment.html

== List all docker images
  docker image ls

== List all docker containers
  docker ps -a

// -------------------------------

== Start ==

docker-compose up

// -------------------------------

== Stop ==

docker-compose stop

// -------------------------------

== Remove ==
=== Remove all containers
  docker rm $(docker ps -a -q)

=== Remove all Kafka containers
    Note: they need to be stopped
      docker stop `docker ps -a | grep kafka- | awk '{print $1}'`
      docker rm -v `docker ps -a | grep kafka- | awk '{print $1}'`

=== Remove all Zookeeper containers
    Note: All containers depend on Zookeeper, so stop all containers first
      docker stop $(docker ps -a -q)
      docker rm -v `docker ps -a | grep zk- | awk '{print $1}'`

=== Prune docker Volumes and non-running containers
  docker system prune
  docker system prune --volumes

// -------------------------------




== Necessary environment
IMPORTANT: Set `PATH` For the commands below to work

  export PATH=$PATH:/opt/confluent-5.0.1/bin

== Zookeeper

ZOOKEEPER_SERVERS -> leaderport:electionport (source: https://docs.confluent.io/current/zookeeper/deployment.html)
leaderport is used by followers to connect to the active leader. This port should be open between all ZooKeeper ensemble members.
electionport is used to perform leader elections between ensemble members. This port should be open between all ZooKeeper ensemble members.

=== Check ZooKeeper

....

for i in 22181 32181 42181; do
  echo stat | nc localhost $i | grep Mode
done

....

//-------------------------------------------------

== Kafka

Test Kafka brokers:

....

for i in 60001 60002 60003; do
    echo "Port: $i:"
    kafka-run-class kafka.tools.JmxTool \
    --jmx-url service:jmx:rmi:///jndi/rmi://localhost:$i/jmxrmi \
    --object-name kafka.server:type=KafkaServer,name=BrokerState \
    --one-time true --report-format properties 2>&1 | grep BrokerState
done

....

https://github.com/apache/kafka/blob/trunk/core/src/main/scala/kafka/server/BrokerStates.scala

....

NotRunning                      0
Starting                        1
RecoveringFromUncleanShutdown   2
RunningAsBroker                 3
PendingControlledShutdown       6
BrokerShuttingDown              7

....

//-------------------------------------------------

== Schema Registry

=== Test Schema Registry

  curl localhost:8081/subjects

  docker logs schema-registry

//-------------------------------------------------

== Kafka Manager

Go to
http://localhost:9000

=== Adding the Cluster
....

Cluster-name: kafka-docker
Cluster Zookeeper Hosts: zk-1:22181,zk-2:32181,zk-3:42181
Enable JMX Polling...: Check
Poll consumer information (Not recommended for large # of consumers): Check

....
//-------------------------------------------------

== Topics

=== Create a Topic

....

TOPIC_NAME=foo
kafka-topics --create \
    --topic $TOPIC_NAME \
    --partitions 1 \
    --replication-factor 3 \
    --if-not-exists \
    --config min.insync.replicas=2 \
    --zookeeper localhost:22181,localhost:32181,localhost:42181

....

=== List All Topics

  kafka-topics --list --zookeeper localhost:22181,localhost:32181,localhost:42181

=== Remove all User Topics (keep internal, those starting with '_')
....

for TOPIC_TO_REMOVE in `kafka-topics --list --zookeeper localhost:32181 | grep -v '^_'`; do
    kafka-topics --delete \
        --topic $TOPIC_TO_REMOVE \
        --zookeeper localhost:22181,localhost:32181,localhost:42181
done

....

=== Describe Topic
....

TOPIC_NAME=foo
docker run \
    --net=host \
    --rm \
    confluentinc/cp-kafka:5.1.0 \
    kafka-topics --describe --topic $TOPIC_NAME --zookeeper localhost:22181,localhost:32181,localhost:42181

....
=== Produce Data to Topic
....

TOPIC_NAME=foo
kafka-console-producer --broker-list localhost:29092,localhost:39092,localhost:49092 --topic $TOPIC_NAME

....
=== Consume data from topic
....

TOPIC_NAME=foo
kafka-console-consumer --bootstrap-server localhost:29092,localhost:39092,localhost:49092 --topic $TOPIC_NAME --from-beginning

....
== Run interactive shell

....

docker exec -it zk-1 bash

....