== Source
https://docs.confluent.io/current/installation/docker/docs/installation/clustered-deployment.html

== Create machine
  docker-machine create --driver virtualbox --virtualbox-memory 6000 confluent

== List machines
  docker-machine ls

== Find IP of machines
  docker-machine ls

== Switch to machine
  eval `docker-machine env confluent`

== List all docker images
  docker image ls

== List all docker containers
  docker ls container -a

// -------------------------------

== Start ==
=== Start all Zookeepers
  docker start `docker ps -a | grep zk- | awk '{print $1}'`

=== Start all Kafka containers
  docker start `docker ps -a | grep kafka- | awk '{print $1}'`

=== Start a Docker instance
  docker start zk-1

// -------------------------------

== Stop ==
=== Stop all containers
  docker stop $(docker ps -a -q)

=== Stop all Zookeepers
  docker stop `docker ps -a | grep zk- | awk '{print $1}'`

=== Stop all Kafka instances
docker stop `docker ps -a | grep kafka- | awk '{print $1}'`

// -------------------------------

== Remove ==
=== Remove all containers
  docker rm $(docker ps -a -q)

  === Remove all Kafka containers
    Note: they need to be stopped
      docker stop `docker ps -a | grep kafka- | awk '{print $1}'`
      docker rm -v `docker ps -a | grep kafka- | awk '{print $1}'`

  === Remove all Zookeeper containers
    Note: All containers depend on Zookeeper, so stop all containers first
      docker stop $(docker ps -a -q)
      docker rm -v `docker ps -a | grep zk- | awk '{print $1}'`

=== Prune docker Volumes and non-running containers
  docker system prune
  docker system prune --volumes

// -------------------------------

== Necessary environment
IMPORTANT: Set `CONFLUENT_DOCKER_IP` For the commands below to work

`export CONFLUENT_DOCKER_IP=`docker-machine ip confluent``

== Zookeeper

IMPORTANT: Set `CONFLUENT_DOCKER_IP` For the commands below to work

ZOOKEEPER_SERVERS -> leaderport:electionport (source: https://docs.confluent.io/current/zookeeper/deployment.html)
leaderport is used by followers to connect to the active leader. This port should be open between all ZooKeeper ensemble members.
electionport is used to perform leader elections between ensemble members. This port should be open between all ZooKeeper ensemble members.

`export CONFLUENT_DOCKER_IP=`docker-machine ip confluent``
....
  docker run -d \
    --net=host \
    --name=zk-1 \
    -e ZOOKEEPER_SERVER_ID=1 \
    -e ZOOKEEPER_CLIENT_PORT=22181 \
    -e KAFKA_JMX_PORT=29999 \
    -e KAFKA_JMX_HOSTNAME=`docker-machine ip confluent` \
    -e ZOOKEEPER_TICK_TIME=2000 \
    -e ZOOKEEPER_INIT_LIMIT=5 \
    -e ZOOKEEPER_SYNC_LIMIT=2 \
    -e ZOOKEEPER_SERVERS="$CONFLUENT_DOCKER_IP:22888:23888;$CONFLUENT_DOCKER_IP:32888:33888;$CONFLUENT_DOCKER_IP:42888:43888" \
    confluentinc/cp-zookeeper:5.1.0
....
....
  docker run -d \
    --net=host \
    --name=zk-2 \
    -e ZOOKEEPER_SERVER_ID=2 \
    -e ZOOKEEPER_CLIENT_PORT=32181 \
    -e KAFKA_JMX_PORT=39999 \
    -e KAFKA_JMX_HOSTNAME=`docker-machine ip confluent` \
    -e ZOOKEEPER_TICK_TIME=2000 \
    -e ZOOKEEPER_INIT_LIMIT=5 \
    -e ZOOKEEPER_SYNC_LIMIT=2 \
    -e ZOOKEEPER_SERVERS="$CONFLUENT_DOCKER_IP:22888:23888;$CONFLUENT_DOCKER_IP:32888:33888;$CONFLUENT_DOCKER_IP:42888:43888" \
    confluentinc/cp-zookeeper:5.1.0
....
....
docker run -d \
   --net=host \
   --name=zk-3 \
   -e ZOOKEEPER_SERVER_ID=3 \
   -e ZOOKEEPER_CLIENT_PORT=42181 \
   -e KAFKA_JMX_PORT=49999 \
   -e KAFKA_JMX_HOSTNAME=`docker-machine ip confluent` \
   -e ZOOKEEPER_TICK_TIME=2000 \
   -e ZOOKEEPER_INIT_LIMIT=5 \
   -e ZOOKEEPER_SYNC_LIMIT=2 \
   -e ZOOKEEPER_SERVERS="$CONFLUENT_DOCKER_IP:22888:23888;$CONFLUENT_DOCKER_IP:32888:33888;$CONFLUENT_DOCKER_IP:42888:43888" \
   confluentinc/cp-zookeeper:5.1.0
....
=== Check ZooKeeper

....
for i in 22181 32181 42181; do
  docker run --net=host --rm confluentinc/cp-zookeeper:5.1.0 bash -c "echo stat | nc localhost $i | grep Mode"
done
....
//-------------------------------------------------

== Kafka

IMPORTANT: Set `CONFLUENT_DOCKER_IP` For the commands below to work

`export CONFLUENT_DOCKER_IP=`docker-machine ip confluent``
....
  docker run -d \
    --net=host \
    --name=kafka-1 \
    -e KAFKA_JMX_PORT=60001 \
    -e KAFKA_JMX_HOSTNAME=`docker-machine ip confluent` \
    -e KAFKA_ZOOKEEPER_CONNECT=$CONFLUENT_DOCKER_IP:22181,$CONFLUENT_DOCKER_IP:32181,$CONFLUENT_DOCKER_IP:42181 \
    -e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://$CONFLUENT_DOCKER_IP:29092 \
    -e KAFKA_MIN_INSYNC_REPLICAS=2 \
    -e KAFKA_AUTO_CREATE_TOPICS_ENABLE=false \
    -e KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE=false \
    confluentinc/cp-kafka:5.1.0
....
....
docker run -d \
  --net=host \
  --name=kafka-2 \
  -e KAFKA_JMX_PORT=60002 \
  -e KAFKA_JMX_HOSTNAME=`docker-machine ip confluent` \
  -e KAFKA_ZOOKEEPER_CONNECT=$CONFLUENT_DOCKER_IP:22181,$CONFLUENT_DOCKER_IP:32181,$CONFLUENT_DOCKER_IP:42181 \
  -e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://$CONFLUENT_DOCKER_IP:39092 \
  -e KAFKA_MIN_INSYNC_REPLICAS=2 \
  -e KAFKA_AUTO_CREATE_TOPICS_ENABLE=false \
  -e KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE=false \
  confluentinc/cp-kafka:5.1.0
....
....
  docker run -d \
    --net=host \
    --name=kafka-3 \
    -e KAFKA_JMX_PORT=60003 \
    -e KAFKA_JMX_HOSTNAME=`docker-machine ip confluent` \
    -e KAFKA_ZOOKEEPER_CONNECT=$CONFLUENT_DOCKER_IP:22181,$CONFLUENT_DOCKER_IP:32181,$CONFLUENT_DOCKER_IP:42181 \
    -e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://$CONFLUENT_DOCKER_IP:49092 \
    -e KAFKA_MIN_INSYNC_REPLICAS=2 \
    -e KAFKA_AUTO_CREATE_TOPICS_ENABLE=false \
    -e KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE=false \
    confluentinc/cp-kafka:5.1.0
....
//-------------------------------------------------

== Schema Registry

IMPORTANT: Set `CONFLUENT_DOCKER_IP` For the commands below to work

`export CONFLUENT_DOCKER_IP=`docker-machine ip confluent``
....
  docker run -d \
    --net=host \
    --name=schema-registry \
    -e SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=$CONFLUENT_DOCKER_IP:22181,$CONFLUENT_DOCKER_IP:32181,$CONFLUENT_DOCKER_IP:42181 \
    -e SCHEMA_REGISTRY_HOST_NAME=`docker-machine ip confluent` \
    -e SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081 \
    confluentinc/cp-schema-registry:5.1.0
....
=== Test Schema Registry
  docker logs schema-registry

//-------------------------------------------------

== Kafka Manager

IMPORTANT: Set `CONFLUENT_DOCKER_IP` For the commands below to work

`export CONFLUENT_DOCKER_IP=`docker-machine ip confluent``
....
docker run -d \
  --net=host \
  --name=kafka-manager \
  -p 9000:9000 \
  -e KM_VERSION=1.3.3.18 \
  -e ZK_HOSTS="$CONFLUENT_DOCKER_IP:22181,$CONFLUENT_DOCKER_IP:32181,$CONFLUENT_DOCKER_IP:42181" \
  -e APPLICATION_SECRET=soincrediblyseecret \
  sheepkiller/kafka-manager
....
=== Adding the Cluster
....
Cluster-name: kafka-docker
Cluster Zookeeper Hosts: 192.168.99.100:22181,192.168.99.100:32181,192.168.99.100:42181
Enable JMX Polling...: Check
brokerViewThreadPoolSize: 2
offsetCacheThreadPoolSize: 2
kafkaAdminClientThreadPoolSize: 2
....
//-------------------------------------------------

== Topics

=== Create a Topic

IMPORTANT: SET ENV BELOW

 TOPIC_NAME=foo

....
docker run \
  --net=host \
  --rm \
  confluentinc/cp-kafka:5.1.0 \
  kafka-topics --create \
    --topic $TOPIC_NAME \
    --partitions 1 \
    --replication-factor 3 \
    --if-not-exists \
    --config min.insync.replicas=2 \
    --zookeeper localhost:32181
....

=== List Topics including internal topics
....
docker run \
    --net=host \
    --rm \
    confluentinc/cp-kafka:5.1.0 \
    kafka-topics --list --zookeeper localhost:32181
....

=== List Topics without internal topics
....
docker run \
    --net=host \
    --rm \
    confluentinc/cp-kafka:5.1.0 \
    kafka-topics --list --exclude-internal --zookeeper localhost:32181
....

=== Remove all Topics but keep internal topics
....

CONFLUENT_DOCKER_IP=`docker-machine ip confluent`

for TOPIC_NAME in \
`docker run \
    --net=host \
    --rm \
    confluentinc/cp-kafka:5.1.0 \
    kafka-topics --list --exclude-internal --zookeeper localhost:32181`
do
    docker run \
    --net=host \
    --rm \
    confluentinc/cp-kafka:5.1.0 \
    kafka-topics --delete \
    --topic $TOPIC_NAME \
    --zookeeper $CONFLUENT_DOCKER_IP:32181
done

....

=== Describe Topic
....
docker run \
    --net=host \
    --rm \
    confluentinc/cp-kafka:5.1.0 \
    kafka-topics --describe --topic $TOPIC_NAME --zookeeper localhost:32181
....
=== Generate Data to Topic
....
docker run \
  --net=host \
  --rm confluentinc/cp-kafka:5.1.0 \
  bash -c "seq 42 | kafka-console-producer --broker-list localhost:29092 --topic $TOPIC_NAME && echo 'Produced 42 messages.'"
....
=== Receive Data
....
docker run \
 --net=host \
 --rm \
 confluentinc/cp-kafka:5.1.0 \
 kafka-console-consumer --bootstrap-server localhost:29092 --topic $TOPIC_NAME --from-beginning --max-messages 42
....
== Run interactive shell
