== Problem

=== Fel 1
 [2018-12-17 07:31:03,995] INFO [ReplicaFetcher replicaId=1008, leaderId=1007, fetcherId=0] Retrying leaderEpoch request for partition __consumer_offsets-32 as the leader reported an error: UNKNOWN_SERVER_ERROR (kafka.server.ReplicaFetcherThread)

* Löste sig när jag uppdaterade image till 5.1.0

=== När jag auto-skapade ett topic fick jag detta på klientsidan
....
2018-12-18 09:07:43 DEBUG FetchSessionHandler:421 - [Consumer clientId=consumer-1, groupId=autocreateconsumer2] Node 1001 sent an incremental fetch response for session 1403653342 with 0 response partition(s), 1 implied partition(s)
2018-12-18 09:07:43 DEBUG Fetcher:898 - [Consumer clientId=consumer-1, groupId=autocreateconsumer2] Added READ_UNCOMMITTED fetch request for partition non-existent-topic2-0 at offset 229 to node 192.168.99.100:29092 (id: 1001 rack: null)
2018-12-18 09:07:43 DEBUG FetchSessionHandler:250 - [Consumer clientId=consumer-1, groupId=autocreateconsumer2] Built incremental fetch (sessionId=1403653342, epoch=729) for node 1001. Added 0 partition(s), altered 0 partition(s), removed 0 partition(s) out of 1 partition(s)
2018-12-18 09:07:43 DEBUG Fetcher:218 - [Consumer clientId=consumer-1, groupId=autocreateconsumer2] Sending READ_UNCOMMITTED IncrementalFetchRequest(toSend=(), toForget=(), implied=(non-existent-topic2-0)) to broker 192.168.99.100:29092 (id: 1001 rack: null)
2018-12-18 09:07:43 DEBUG FetchSessionHandler:421 - [Consumer clientId=consumer-1, groupId=autocreateconsumer2] Node 1001 sent an incremental fetch response for session 1403653342 with 0 response partition(s), 1 implied partition(s)
2018-12-18 09:07:43 DEBUG Fetcher:898 - [Consumer clientId=consumer-1, groupId=autocreateconsumer2] Added READ_UNCOMMITTED fetch request for partition non-existent-topic2-0 at offset 229 to node 192.168.99.100:29092 (id: 1001 rack: null)
2018-12-18 09:07:43 DEBUG FetchSessionHandler:250 - [Consumer clientId=consumer-1, groupId=autocreateconsumer2] Built incremental fetch (sessionId=1403653342, epoch=730) for node 1001. Added 0 partition(s), altered 0 partition(s), removed 0 partition(s) out of 1 partition(s)
2018-12-18 09:07:43 DEBUG Fetcher:218 - [Consumer clientId=consumer-1, groupId=autocreateconsumer2] Sending READ_UNCOMMITTED IncrementalFetchRequest(toSend=(), toForget=(), implied=(non-existent-topic2-0)) to broker 192.168.99.100:29092 (id: 1001 rack: null)
2018-12-18 09:07:44 DEBUG FetchSessionHandler:421 - [Consumer clientId=consumer-1, groupId=autocreateconsumer2] Node 1001 sent an incremental fetch response for session 1403653342 with 0 response partition(s), 1 implied partition(s)
2018-12-18 09:07:44 DEBUG Fetcher:898 - [Consumer clientId=consumer-1, groupId=autocreateconsumer2] Added READ_UNCOMMITTED fetch request for partition non-existent-topic2-0 at offset 229 to node 192.168.99.100:29092 (id: 1001 rack: null)
2018-12-18 09:07:44 DEBUG FetchSessionHandler:250 - [Consumer clientId=consumer-1, groupId=autocreateconsumer2] Built incremental fetch (sessionId=1403653342, epoch=731) for node 1001. Added 0 partition(s), altered 0 partition(s), removed 0 partition(s) out of 1 partition(s)
2018-12-18 09:07:44 DEBUG Fetcher:218 - [Consumer clientId=consumer-1, groupId=autocreateconsumer2] Sending READ_UNCOMMITTED IncrementalFetchRequest(toSend=(), toForget=(), implied=(non-existent-topic2-0)) to broker 192.168.99.100:29092 (id: 1001 rack: null)
....
==== Lösning
Kolla fetch request. Det görs till sista offset i Topicet (229)

Lägg till följande i consumern:
....
props.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest");
props.put("group.id", "dynamic-" + System.currentTimeMillis());
Note: Båda behövs för att få meddelanden från början
....

Annars ser man:

 2018-12-18 10:29:31 INFO  org.apache.kafka.clients.consumer.internals.Fetcher:583 - [Consumer clientId=consumer-1, groupId=dynamic-1545125368172] Resetting offset for partition everything-topic-0 to offset 90.

Notera offset 90, det fanns 90 meddelanden på topicet


== Fel 2

 [2018-12-19 07:31:09,642] WARN [Producer clientId=producer-1] 1 partitions have leader brokers without a matching listener, including [__confluent.support.metrics-0] (org.apache.kafka.clients.NetworkClient)

== Fel 3
 $ docker-machine env confluent
 Error checking TLS connection: Host is not running

=== Lösning
Körde

 $ docker-machine restart confluent

När jag körde

 $ docker-machine ls
 NAME        ACTIVE   DRIVER       STATE     URL   SWARM   DOCKER    ERRORS
 confluent   -        virtualbox   Stopped                 Unknown

Så står det iofs att "STATE" är "Stopped". Kanske räcker det med 'start' istället för 'restart' i
docker-machine-kommandot

== Fel 3
När man kör

 $ docker-machine create --driver virtualbox --virtualbox-memory 6000 confluent

får man

 ...
 ubuntu 18.04 "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path"
 ...

Lösning:

Laddade hem docker-machine från
https://github.com/docker/machine/releases/tag/v0.16.0
Döpte om, chmoddade och kopierade in till rätt ställe

 $ chmod 755 docker-machine-Linux-x86_64
 $ sudo mv docker-machine-Linux-x86_64 /usr/local/bin/docker-machine

Nu funkade docker-machine create-kommandot!!

== Fel 4
Streams Consumer får inga meddelanden

    xxx.foreach(...)

måste komma före

    final KafkaStreams streams = new KafkaStreams(builder.build(), streamsConfiguration);

== Stacktrace

Om man har samma application-id för två applikationer som inte är samma applikation,
dvs de konsumerar inte från samma topics mm

2019-01-11 09:24:06 INFO  org.apache.kafka.clients.consumer.internals.AbstractCoordinator:486 - [Consumer clientId=application1-a2d06eb5-1a51-4b66-9d9b-629e37ca7a40-StreamThread-1-consumer, groupId=application1] (Re-)joining group
2019-01-11 09:24:06 DEBUG org.apache.kafka.streams.processor.internals.InternalTopologyBuilder:1875 - stream-thread [application1-a2d06eb5-1a51-4b66-9d9b-629e37ca7a40-StreamThread-1] found [counter-topic] topics possibly matching regex
2019-01-11 09:24:06 DEBUG org.apache.kafka.streams.processor.internals.InternalTopologyBuilder:1233 - stream-thread [application1-a2d06eb5-1a51-4b66-9d9b-629e37ca7a40-StreamThread-1] updating builder with SubscriptionUpdates{updatedTopicSubscriptions=[counter-topic]} topic(s) with possible matching regex subscription(s)
2019-01-11 09:24:12 INFO  org.apache.kafka.clients.consumer.internals.AbstractCoordinator:486 - [Consumer clientId=application1-a2d06eb5-1a51-4b66-9d9b-629e37ca7a40-StreamThread-1-consumer, groupId=application1] (Re-)joining group
2019-01-11 09:24:12 INFO  org.apache.kafka.clients.consumer.internals.AbstractCoordinator:450 - [Consumer clientId=application1-a2d06eb5-1a51-4b66-9d9b-629e37ca7a40-StreamThread-1-consumer, groupId=application1] Successfully joined group with generation 3
2019-01-11 09:24:12 ERROR org.apache.kafka.streams.processor.internals.StreamThread:755 - stream-thread [application1-a2d06eb5-1a51-4b66-9d9b-629e37ca7a40-StreamThread-1] Encountered the following error during processing:
java.lang.IllegalArgumentException: Assigned partition stats-topic-1 for non-subscribed topic regex pattern; subscription pattern is application1-KSTREAM-AGGREGATE-STATE-STORE-0000000002-repartition|counter-topic
	at org.apache.kafka.clients.consumer.internals.SubscriptionState.assignFromSubscribed(SubscriptionState.java:187)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinComplete(ConsumerCoordinator.java:250)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:406)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:340)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:341)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1214)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1179)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1164)
	at org.apache.kafka.streams.processor.internals.StreamThread.pollRequests(StreamThread.java:913)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:818)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:777)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:747)
2019-01-11 09:24:12 INFO  org.apache.kafka.streams.processor.internals.StreamThread:207 - stream-thread [application1-a2d06eb5-1a51-4b66-9d9b-629e37ca7a40-StreamThread-1] State transition from PARTITIONS_REVOKED to PENDING_SHUTDOWN
2019-01-11 09:24:12 INFO  org.apache.kafka.streams.processor.internals.StreamThread:1178 - stream-thread [application1-a2d06eb5-1a51-4b66-9d9b-629e37ca7a40-StreamThread-1] Shutting down
2019-01-11 09:24:12 DEBUG org.apache.kafka.streams.processor.internals.TaskManager:256 - stream-thread [application1-a2d06eb5-1a51-4b66-9d9b-629e37ca7a40-StreamThread-1] Shutting down all active tasks [], standby tasks [], suspended tasks [], and suspended standby tasks []
2019-01-11 09:24:12 INFO  org.apache.kafka.clients.consumer.KafkaConsumer:1031 - [Consumer clientId=application1-a2d06eb5-1a51-4b66-9d9b-629e37ca7a40-StreamThread-1-restore-consumer, groupId=] Unsubscribed all topics or patterns and assigned partitions
2019-01-11 09:24:12 INFO  org.apache.kafka.clients.producer.KafkaProducer:1136 - [Producer clientId=application1-a2d06eb5-1a51-4b66-9d9b-629e37ca7a40-StreamThread-1-producer] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
2019-01-11 09:24:12 DEBUG org.apache.kafka.clients.producer.internals.Sender:239 - [Producer clientId=application1-a2d06eb5-1a51-4b66-9d9b-629e37ca7a40-StreamThread-1-producer] Beginning shutdown of Kafka producer I/O thread, sending remaining records.
2019-01-11 09:24:12 DEBUG org.apache.kafka.clients.producer.internals.Sender:263 - [Producer clientId=application1-a2d06eb5-1a51-4b66-9d9b-629e37ca7a40-StreamThread-1-producer] Shutdown of Kafka producer I/O thread has completed.
2019-01-11 09:24:12 DEBUG org.apache.kafka.clients.producer.KafkaProducer:1181 - [Producer clientId=application1-a2d06eb5-1a51-4b66-9d9b-629e37ca7a40-StreamThread-1-producer] Kafka producer has been closed
Exception in thread "application1-a2d06eb5-1a51-4b66-9d9b-629e37ca7a40-StreamThread-1" java.lang.IllegalArgumentException: Assigned partition stats-topic-1 for non-subscribed topic regex pattern; subscription pattern is application1-KSTREAM-AGGREGATE-STATE-STORE-0000000002-repartition|counter-topic
	at org.apache.kafka.clients.consumer.internals.SubscriptionState.assignFromSubscribed(SubscriptionState.java:187)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinComplete(ConsumerCoordinator.java:250)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:406)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:340)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:341)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1214)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1179)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1164)
	at org.apache.kafka.streams.processor.internals.StreamThread.pollRequests(StreamThread.java:913)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:818)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:777)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:747)
2019-01-11 09:24:12 INFO  org.apache.kafka.streams.processor.internals.StreamThread:207 - stream-thread [application1-a2d06eb5-1a51-4b66-9d9b-629e37ca7a40-StreamThread-1] State transition from PENDING_SHUTDOWN to DEAD
2019-01-11 09:24:12 INFO  org.apache.kafka.streams.KafkaStreams:257 - stream-client [application1-a2d06eb5-1a51-4b66-9d9b-629e37ca7a40] State transition from REBALANCING to ERROR
2019-01-11 09:24:12 WARN  org.apache.kafka.streams.KafkaStreams:418 - stream-client [application1-a2d06eb5-1a51-4b66-9d9b-629e37ca7a40] All stream threads have died. The instance will be in error state and should be closed.
2019-01-11 09:24:12 INFO  org.apache.kafka.streams.processor.internals.StreamThread:1198 - stream-thread [application1-a2d06eb5-1a51-4b66-9d9b-629e37ca7a40-StreamThread-1] Shutdown complete


== IP Problem i Docker

....
Körde ZooKeeper:
$   docker run -d \
>     --name=zk-1 \
>     --net=host \
>     -e ZOOKEEPER_SERVER_ID=1 \
>     -e ZOOKEEPER_CLIENT_PORT=22181 \
>     -e KAFKA_JMX_PORT=29999 \
>     -e KAFKA_JMX_HOSTNAME=localhost \
>     -e ZOOKEEPER_TICK_TIME=2000 \
>     -e ZOOKEEPER_INIT_LIMIT=5 \
>     -e ZOOKEEPER_SYNC_LIMIT=2 \
>     -e ZOOKEEPER_SERVERS="localhost:22888:23888;localhost:32888:33888;localhost:42888:43888" \
>     confluentinc/cp-zookeeper:5.1.0
fca46874c504cc9286195e5aea7242e39b88e72935c6a7115d5b18ea9fa9fd21
Tallahassee:Downloads mats$ docker logs zk-1

...

1===> Launching zookeeper ...
Error: Exception thrown by the agent : java.net.MalformedURLException: Local host name unknown: java.net.UnknownHostException: linuxkit-025000000001: linuxkit-025000000001: Name or service not known
sun.management.AgentConfigurationError: java.net.MalformedURLException: Local host name unknown: java.net.UnknownHostException: linuxkit-025000000001: linuxkit-025000000001: Name or service not known
	at sun.management.jmxremote.ConnectorBootstrap.startRemoteConnectorServer(ConnectorBootstrap.java:480)
	at sun.management.Agent.startAgent(Agent.java:262)
	at sun.management.Agent.startAgent(Agent.java:452)
Caused by: java.net.MalformedURLException: Local host name unknown: java.net.UnknownHostException: linuxkit-025000000001: linuxkit-025000000001: Name or service not known
	at javax.management.remote.JMXServiceURL.<init>(JMXServiceURL.java:289)
	at javax.management.remote.JMXServiceURL.<init>(JMXServiceURL.java:253)
	at sun.management.jmxremote.ConnectorBootstrap.exportMBeanServer(ConnectorBootstrap.java:739)
	at sun.management.jmxremote.ConnectorBootstrap.startRemoteConnectorServer(ConnectorBootstrap.java:468)
	... 2 more
....

Lösning: La till linuxkit-025000000001 i /etc/hosts:

....
127.0.0.1       localhost linuxkit-025000000001
....

== Kan inte connecta till kafka-manager på port 9000

Contaiers i Docker för mac kan inte forwarda portar eftersom
containrarna kör på en virtuell maskin

referens:
https://docs.docker.com/docker-for-mac/networking/

