== Komma igång

Nedan följer instruktioner för att komma igång. Förhoppningsvis ska allt gå utan problem, annars får vi lösa det på kompetensdagen.
Utför stegen nedan och håll tummarna för att det fungerar!

=== Installera docker och docker-compose
Installera på det bästa sättet för din plattform

=== Installera Confluent Platform

Confluent Platform distribueras som en tarboll eller zip. Den laddas hem från Confluents hemsida.

Surfa till https://www.confluent.io/download, klicka på "Download Version 5.1.2" och följ instruktionerna
Packa upp distributionen och sätt PATH.

  $ unzip confluent-5.1.2-2.11.zip
  $ cd confluent-5.1.2/bin
  $ export PATH=$PATH:`pwd`

NOTE: Det är viktigt att sätta PATH till `.../confluent-5.1.2/bin` för att kafkakommandona (t.ex. kafka-topics och kafka-console-producer mm)
som används i labbarna ska fungera

=== Kompetensdagsrepot

Klona repot

  $ git clone https://github.com/ryzlab/kafka-kompetensdag.git

=== Starta kafkaklustret
Starta kafkaklustret. Klustret består av 3 ZooKeeper, 3 KafkaBrokers, Schema Registry och Kafka Manager

  $ cd kafka-kompetensdag
  $ docker-compose up

=== Testa Kafka-Manager

Nu ska det gå att surfa till Kafka-Manager, ett Web-UI för att hantera Kafkakluster.
Testa att surfa till http://localhost:9000. Vi konfigurerar på kompetensdagen, men sidan ska gå att nå.

=== Testa ZooKeeper

Det ska även gå att kommunicera med Zookeeper för att t.ex. lista skapade topics:

  $ kafka-topics --list --zookeeper localhost:32181
  _schemas

=== Testa Kafka

Skapa ett Topic, foo
  $ kafka-topics --create --topic foo --partitions 1 --replication-factor 3 --if-not-exists --config min.insync.replicas=2 --zookeeper localhost:32181

Skicka några meddelanden med kafka-console-producer. Kör kommandot och skriv några rader text, avsluta med CTRL+D

  $ kafka-console-producer --broker-list localhost:29092 --topic foo

Kör en consumer för att få ut meddelandena

  $ kafka-console-consumer --bootstrap-server localhost:29092 --topic foo --from-beginning

Avsluta med CTRL+C

YES!!! Redo!


